# The Time-Complexity and Space-Complexity of Dictionaries in Python ;

# insert :
""" Time Complexity : O(1) because we can directly access the element using its key and
 we are not using any extra space to insert the element."""
 
# delete :
""" Time Complexity : O(1) because we can directly access the element using its key ."""

# search :
""" Time Complexity : O(1) because we can directly access the element using its key ."""

# Worst Case Time Complexity :   hash collision :

"""Worst Case Time Complexity : O(n) because in case of a hash collision, we need to traverse the linked list to find the element and insert it. """


